---
title: Week 2 - Probability Review
sitetitle: Week 2
summary: "EC200 - Week 2 Probability Review (SW Chapter 2)"

date: "2020-08-19"
start_date: "2020-09-07"
end_date: "2020-09-11"
menu:
  content:
    parent: Course content
    weight: 1
  
  # Academic page type (do not modify).
type: docs
## Slides

#pdf: /slides/ch02-slides.pdf
# thumb: /slides/ch02-slides.png
output:
  blogdown::html_page:
    toc: true

pdf: /slides/ch2-slides.pdf
thumb: /slides/ch2-slides.png

---


## Overview

Welcome to Week 1! Our goal this week is to (1) help us sort out our varying technologies and workflows and (2) review some statistics! Basically, this is week 1 of a two-week mini-bootcamp to get us ready for the glorious world of regressions!

What you should do this week and the next week depends on your background:

### I took EC170/STAT141 recently and remember some stuff
1. Read through SW, and dig deeper into anything that doesn't look familiar. 
2. Watch the class videos. 
3. Use the Khan Academy to clarify anything you feel a bit fuzzy on. 
4. Make sure you can do the practice problems. 


### Everyone else
1. Start by reviewing the Khan Academy videos 
2. Work through *all* the Khan Academy practice problems. 
3. Watch the class videos 
4. Head into the practice problems, and review concepts where you are still stuck.


## Reading Guide

**Chapter 2: Review of Probability**

This is the material you should know,  along with supports from [Khan Academy (<i class="fas fa-tv"> </i>)](https://www.khanacademy.org/math/ap-statistics/). Remember that you don't need to memorize formulas! 



- SW 2.1 Random Variables and Probability Distributions 
  - [<i class="fas fa-tv"> </i> Discrete random variables](https://www.khanacademy.org/math/ap-statistics/random-variables-ap#discrete-random-variables)
  - [<i class="fas fa-tv"> </i> Continuous random variables](https://www.khanacademy.org/math/ap-statistics/random-variables-ap#continuous-random-variables)
   - [<i class="fas fa-tv"> </i> Conditional probability](https://www.khanacademy.org/math/ap-statistics/probability-ap#stats-conditional-probability)
- SW 2.2 Expected Values, Mean, and Variance 
  - You only need a general knowledge of kurtosis and skew. 
  - [<i class="fas fa-tv"> </i> Transforming random variables](https://www.khanacademy.org/math/ap-statistics/random-variables-ap/transforming-random-variables/v/impact-of-scaling-and-shifting-random-variables)
- SW 2.3 Two Random Variables 
  - Law of iterated expectations can be skimmed 
	- Make sure you’re good with key concept box 2.3!
  - [<i class="fas fa-tv"> </i> Combining random variables](https://www.khanacademy.org/math/ap-statistics/random-variables-ap#combining-random-variables)
- SW 2.4 The Normal, Chi-Squared, Student t, and F distributions 
  - Normal distribution ~~and t-distribution~~ only. We won’t use chi-squared, and we’ll come back to F-distributions later. For any work we'll be doing, our sample sizes will be greater than 100, so $t \rightarrow z$. 
  - [<i class="fas fa-tv"> </i> Normal distributions and the empirical rule](https://www.khanacademy.org/math/ap-statistics/density-curves-normal-distribution-ap#stats-normal-distributions)
  - [ <i class="fas fa-tv"> </i> Normal distribution calculations](https://www.khanacademy.org/math/ap-statistics/density-curves-normal-distribution-ap#normal-distributions-calculations)
- SW 2.5 Random Sampling and the Distribution of the Sample Average 
  - [ <i class="fas fa-tv"> </i> What is a sampling distribution?](https://www.khanacademy.org/math/ap-statistics/sampling-distribution-ap#what-is-sampling-distribution)
  
- SW 2.6 Large-sample approximations to sampling distributions
  - *Get that central limit theorem!*
  - [ <i class="fas fa-tv"> </i> Sampling distribution of a sample   mean](https://www.khanacademy.org/math/ap-statistics/sampling-distribution-ap#sampling-distribution-mean) (relevant for 2.5 as well)
    
## Slides

`r blogdown::shortcode("slides")`

## Videos

- [Probability Review - SW 2.1-2.3](https://youtu.be/SYc3ccB872s)

_Sorry that the audio is bit fuzzy at the beginning - I'm still learning!_
`r htmltools::HTML("{{< youtube SYc3ccB872s >}}")`


- [Conditional Probability Example](https://youtu.be/7CKOMFXqlXE)
`r htmltools::HTML("{{< youtube 7CKOMFXqlXE >}}")`


