

---
title: Exam 1
sitetitle: Exam 1
summary: "EC200 - Exam 1 Prep (EC200) "

date: "2020-10-17"


  
  # Academic page type (do not modify).
type: docs
menu:
  content:
    parent: Exam prep
    weight: 3
    
output:
  blogdown::html_page:
    toc: true


pdf: /slides/exam1-review.pdf
thumb: /slides/exam1-review.png


---

## What should I know? 

**The exam covers chapter 4-7** 

Make sure you are comfortable with the material chapter guides from [Week 4](../04-content) and [Week 5](../05-content), [Week 6](../06-content), and [Week 7](../07-content). What does comfortable mean? That you're familiar with definitions and terminology, and that you can work through problems at the level of PS3 and PS4.

I will not ask you to do things in Stata, but I will ask you to interpret results from Stata. 

### Things that I consider "fair game" 
- Thinking about GM assumptions, their implications, and when they may or may not apply.
- Interpreting regression coefficients from regression equations (like $TestScr = 54 + 0.08Age$), from tables (like in PS4), or from raw Stata output.
- Conducting all the sorts of hypothesis tests we've looked at, doing them by hand in the case of t-tests or simple F-tests when we have homoskedasticity.

## How can I prepare? 

A few ideas, depending on where you're feeling least secure: 

- Redo lecture video quizzes^[I'm assuming these are still open for you to attempt. If I'm wrong, please e-mail/message me!], but note that the level of these is simpler than I would ask 
- Work through problem sets and prevous in-class exercises (posted in their respective [content](../../content) section). Do them without looking at your past work!
- Make one-page chapter guides. These are handy resources for the exam and a good way to make sure you've thought about what's important
- Make yourself a formula sheet. Useful to have, and also the act of creating it will help you
- Watch videos/review slides when you have gaps. 



## I need more practice!

I recommend the following resources: 

 - Odd-numbered problems from Stock and Watson - solutions are available [here](../../bonus/general-resources)
 - [Practice exam](#practice-exam)
 - [In-class practice (#inclass-practice)]

## What is the structure of the exam? 

The exam will "go live" during our scheduled class time at **2:20pm on Monday, September 21**.  It will be "due" at **3:20pm the same day.** I've added an extra 10 minutes for scanning/deep breaths, but I didn't add more to avoid conflicts with those who have class at 3:30pm. 

**The actual structure is different from the Stats quiz!** 

You will be asked to work through approximately 3-4 multi-part questions.**I will integrate these questions into a Blackboard test**. There are multiple versions of the exam. 

### How do I submit? 

There are **two pieces**:

1. Start the quiz and work through each question. Enter your answers on Blackboard as it advises. *I recommend making sure you keep a record of your answers in a word doc or piece of paper, in case you have technical difficulties*. 

2. There is a second "assignment" for submitting a scan of your calculations/work (when appropriate, as some questions won't have work to show).  It will be open until **3:45pm**, so you can submit after you finish the exam.   Please use something like [Adobe Scan](https://acrobat.adobe.com/us/en/mobile/scanner-app.html) so that you can submit your work as **just one file in pdf form**^[In the past, I've found that uploading photos yields huge files that are difficult to grade.]

**NOTE:** The extra time to submit a PDF of your work is just intended for submission. I will use this PDF in two ways: (1) to confirm you have done the necessary calculations that led to your answer (I will indicate for which questions this is necessary) and (2) to assign partial credit in the event you answers are incorrect. If there are answers in the PDF that are not reflected in the  Blackboard test, they will not earn you credit. 

#### Details: 

For your scanned pdf of calculations:
 - I will indicate when it's necessary that you show your work. You can include extra stuff if you want, but it's optional.
 - PDF version - review in advance to make sure the text is readable.
 - Make sure your answers are numbered, but you don't need to write out the questions.
 - Please make sure pages are in order.
 - **YOU MUST SHOW YOUR WORK** for full credit. 

<!-- ### In-class practice  -->

<!-- [Here are the problems](../EC200-03-01practice.docx) we covered/attempted to cover on Monday, September 14. -->


<!-- And a video with solutions! I recommend working through the problems on your own **first**.  -->

<!-- `r htmltools::HTML("{{< youtube q_NbBSDWcpI >}}")` -->

<!-- Or, download a [pdf of the solutions](../EC200-03-01practice_solutions.pdf) -->


### Practice exam! (For logisitics)

Just to make sure we're feeling good about logistics, I'll post a "practice exam" on Blackboard that will go live at **3:30pm on Wednesday, October 21** (after class) with one question. It has the two-part format discussed above. You can access it, work through the problem, scan it, and upload your work  It will be available until **11:59 pm Thursday**

I'll review your submission and make sure there aren't any problems with viewing your work.  

Completion of the practice exam will be worth 2 points toward the exam (regardless of the accuracy of your answer).

<!---
Following department policy, you will be required to use the Respondus lock-down browser with no back-tracking. 

I will ask you to 
## Responu--what? 

 all exams for the course require you to use the Respondus lock-down browser. This means you must use a Mac/PC for the exam, not a Chromebook or iPad. If this creates any problems for you, reach out to me and we can discuss options. 

From UVM: 
  > The LockDown Browser is like a normal browser, except that once you click “Begin” on your test, it prevents you from opening Word documents, instant messages, or email, and it blocks you from visiting other websites or accessing other parts of the course.
> 
> Important: You must download the browser from the URL below. Even if you have used the LockDown Browser at another school, it won’t work at UVM unless you use this version: [http://www.respondus.com/lockdown/download.php?id=488814272](http://www.respondus.com/lockdown/download.php?id=488814272).
>
> You only need to install it once for all tests in your UVM Bb courses.
> Note that you will need to use the LockDown Browser to see your grades and feedback, as well.
> 

 

## Practice 

On Friday, I'll release an optional "practice" lock-down exam. It will have one practice questions, so we can all experience the glory of online testing. If you complete the pratice lock-down exam, you will earn 2 points toward the exam.

## Helpful materials {#helpful-materials}

Two things that may be useful to you: 

- [Standard Normal Distribution Table](../AppendixTable1_rev.pdf)

- [Formula chart](../Formula-sheet_f20.pdf): Is this all the knowledge you need to know? Of course not! But, this should cover most of the formulas you might need.

--> 

## In-class review and practice 

### Slides (10/19)

`r blogdown::shortcode("slides")`

#### 10/19 Class Recording

<iframe src="https://streaming.uvm.edu/media/embed/zxqotIA/" width="640" height="480" frameborder="0" allowfullscreen></iframe>

### Practice questions (10/21)

#### 10/21 Class Recording

<iframe src="https://streaming.uvm.edu/media/embed/rh2LNzE/" width="640" height="480" frameborder="0" allowfullscreen></iframe>

- [10-21 practice questions](../practice/unitquiz1-practicequestions.pdf)
- [10-21 practice solutions](../practice/unitquiz1-practicequestions-soln.pdf)

## Past exams  {#practice-exam .unnumbered}

Use these for additional practice and to get a sense of the level of questions. However, note three things: 
1. I will not ask multiple choice questions
2. Both classes were TTh classes, with longer exam periods 
3. In these courses, we hadn't yet covered hypothesis tests with multiple restrictions!

<!-- - [Fall 2016 Practice Exam](../PracticeExams/Unit1Quiz_fall2016.pdf) (*Skip 3.h.i, which uses logs*) -->
<!-- - [Fall 2016 Practice Exam Solutions (COMING)]  -->
- [Spring 2018 Practice Exam](../PracticeExams/Unit1Quiz_spring2018.pdf)
- [Spring 2018 Practice Exam Solutions](../PracticeExams/Unit1Quiz_spring2018_soln.pdf) (*I strongly recommend doing the practice exam in its entirety before reviewing the solutions*)


