---
title: "Research Paper: Overview"
linktitle: "01 Overview"
date: "2021-08-30"

menu:
  assignment:
    parent: Research Paper
    weight: 1
type: docs

output:
  blogdown::html_page:
    toc: true

---

One main product of the course is an original research paper you'll
produce that incorporates econometric data using the methods we've
learned in class. 

**You can work alone or in pairs.**

## Learning objectives {#learning-objectives .unnumbered}

-   Develop clear, answerable research questions and link them to
    economic theory.

-   Identify and apply appropriate econometric methods to answer
    research question, recognizing necessary assumptions and limitations

-   Conduct and interpret original data analysis using Stata

-   Strengthen written and oral communication skills

## Topic selection {#topic-selection .unnumbered}

Select a research question that is interesting to you and answerable
with data that you can obtain. Your question should accomplish the
following.

-   It must have clear relevance to economic theory.

-   It must be answerable using data (with a sample size of at least 100, ideally much higher!)

-   It may not be an exact replication of previous work. It may,
    however, be an extension.

-   It must use *cross-sectional* or *panel* data. There are lots of
    interesting time-series questions, but we will not cover these
    topics in EC200.
    
**Where folks get into trouble:** The biggest problem I see is that people get very excited about an interesting question, but they don't necessarily have the data they need. In order for us to be able to have reasonable standard errors and good asymptotic properties, I recommend questions that (a) have a data set you can access and (b) have at least 100 observations. I would strongly discourage you from any country or state cross-sections that don't also have a time component. I also would be wary about studies predicting athlete performance - our methods work well, but the link to economics is often tenuous. 



## Research paper process {#research-paper-process .unnumbered}

### [Research ideas](../idea-proposal) {#research-ideas .unnumbered}

Prepare a set of 3 research ideas. An "idea" only needs to consist of
about 2-3 paragraphs, which should include a research question, a hypothesis, a
proposed data set, and a rough plan of analysis for testing your hypothesis. 

### [Data abstract](../data-abstract)  {#data-preparation .unnumbered}

In research, sometimes questions drive the data we choose, and sometimes
the data we have drive the questions we ask. With only one semester to
build a paper, you may need to let the data take the lead. 

You'll prepare a [``data abstract''](../data-abstract) that includes your research question, a description of your data set, and a set of summary statistics.

### [Research proposal](../research-proposal)  {#research-proposal .unnumbered}

From the list of topics, choose and develop one research idea for your
[research proposal](../research-proposal). You'll Write up a **four- to six-page** proposal (double
spaced, excluding tables) for your research paper. This proposal should
provide as much detail as possible to help me and your classmates assess your
plan and provide useful feedback.


### Peer review {#peer-review .unnumbered}
A classmate will provide a [peer review](../peer-review) of your proposal, providing
feedback to help you turn your proposal into a final paper

### Rough draft (optional)  {#rough-draft-optional .unnumbered}

You may submit one rough draft to me for comments. This is optional, but
I **highly recommend** you do it, because the early deadline can help
you stay on track, and you'll have a chance to get an early sense of how
things are going.

### Presentation {#presentation .unnumbered}

You'll make a brief (5-10 minute) presentation of your paper in the
final week of class. I will provide specifics later.

## Paper components  {#paper-components .unnumbered}

A number of excellent guides can help you put together an effective and
interesting research paper. I've provided a set of [paper resources](/bonus/paper-resources).

In general, it should include the following components: abstract (fewer
than 250 words), introduction, background, methodology, results,
conclusion, references, figures, and tables.

### Parameters {#parameters .unnumbered}

-   All paper elements -- idea proposal, paper proposal, first draft,
    peer review forms, final research paper -- should be submitted
    electronically via Blackboard in Word or PDF format.

-   **Format your tables in Excel or comparable software.** Do not copy and
    paste Stata output.

-   Length requirements vary depending on the number of people in your
    group and are based on the the text of your paper only. A one-person
    project should be 2500-3500 words. A two-person project should be
    3500-4500 words. These guidelines **exclude** the title page,
    abstract, references, figures, and tables.

-   No appendices. If it's important, include it in the paper. If it's
    not, then don't include it.

-   Formatting: 12 pt font, 1\" margins, double spacing, Times New
    Roman. No spaces between paragraphs. Include page numbers.

-   Embed your figure/tables or include them at the end of the paper.
    These do not count towards your length.

-   You must also submit a Stata do-file that replicates your analysis
    and a log-file that shows your results. These do not count toward
    your page limit, and they should be submitted as separate files.

### Deadlines {#deadlines .unnumbered}

See [course schedule](../../schedule) for deadlines. Submit materials by **11:59pm** on
the deadline. Submit all assignments via Blackboard. (Late assignments without an extenson
will be penalized 10\% per day, and they may not receive detailed
feedback.) 
### Grading {#grading .unnumbered}

I will provide formal or informal grading rubrics for each component, so
you have a clear idea of how you'll be graded.


| |||| 
| :------------- | :----------: |  :----------: |  :----------: |  :----------: | 
|  Process 	|                            	|  	|  30\%|
|              		|Research ideas      	|5\% 	|   |
|             		| Data set          	 | 5\% 	|	|   
 |           		|Research proposal 	|  10\%   ||
|          		| Peer review        | 5\%    ||
|         		| Rough draft        | 0\%    ||
|        		| Presentation       | 5\%    ||
|  Final draft	|                          |  | 70\%|


## FAQ {#faq .unnumbered}


-   *How does my group size affect grading?* The grading rubric is the
    same regardless of your group sizes. However, I expect that in a
    larger group, your analysis will go deeper, your review of the
    literature will be more comprehensive, you'll have additional
    robustness or placebo tests, etc. See the page requirements for a
    guide. If you have questions, feel free to talk with me in more
    detail.

-   *Can I turn in a paper with 10 pages of text and 2 tables, or 10
    pages of tables and 5 pages of text?* Sure! The right balance
    between written explanation and figures/tables will depend on your
    topic, but 3-5 figures and tables will usually be about right. What
    matters most is that your paper clearly addresses your research
    question.

-   *How should I format my citations and bibliography?* Consistently.
    APA, Chicago, or MLA is fine.

-   *How much data analysis do I need to do?* You should incorporate
    data analysis to answer your research question or test your
    hypotheses. You may also use data to provide some descriptive
    statistics, however that alone would not be sufficient. Exactly how
    much analysis is involved will depend on the question you pose and
    your approach to answering it.

## Recommendations {#recommendations .unnumbered}

See [paper resources](/bonus/rp-resources) for dataset and topic suggestions.

