---
title: "Research Paper: Presentation"
linktitle: "06 Presentation"
date: "2020-08-28"
due_date: "2020-12-04"
due_time: "11:59 PM"
menu:
  assignment:
    parent: Research Paper
    weight: 8
type: docs
editor_options: 
  chunk_output_type: console
---

**Because timing is so tight, I'm no longer requiring you to view your classmate's presentations - but I will circulate the links and encourage you to do so!**

## Overview 

You'll prepare and deliver a 6-8 minute presentation of your paper, with accompanying slides. This will be one presentation per paper. If you are working with a partner, it should be one set of slides, with both members contributing.

Here is an example slide deck: [Example Presentation!](../materials/example-f20.pptx)

## Guidelines for presentation

 - You can record yourself giving your presentation in any way you see fit. The lowest-effort way to do this is to setting up a Microsoft Teams/Zoom meeting with yourself, share your screen, and recording that. 
 - You can leave your camera off or on, whichever makes you more comfortable. 
 - You should cover the main elements of your paper: 
  1. Introduction 
  2. Research questions 
  3. Background/motivation/related literature 
  4. Data
  5. Empirical strategy
  6. Results 
  7. Limitations/discussion 
  8. Conclusion
  
- It doesn't need to be scripted, but you should have practiced, such that your presentation flows smoothly. 
- Try to avoid reading directly off the slides.
- It should be between 6 and 8 minutes.

- However you record it, you should upload it to a streaming site like [UVM Streaming](https://streaming.uvm.edu/media/), YouTube, or Microsoft Stream. 
  - If you use the MS Teams approach, your recording will be automatically uploaded to Microsoft Stream. You may need to double check the settings to make sure I have permission to watch it. 

 **On Blackboard:** Submit a copy of your slides and a link to the video


## [Presentation Rubric](../materials/Presentation_Rubric_v2.pdf)

Download the presentation rubric [here](../materials/Presentation_Rubric_v2.pdf)

| Total: 48 marks                 | 4 = Excellent                                                                         | 3 =   Satisfactory                                                                                           | 2 = Marginal                                                             | 1 =   Unacceptable                                                                            |
|---------------------------------|---------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| Content (32 marks)              |                                                                                       |                                                                                                              |                                                                          |                                                                                               |
|                                 |                                                                                       |                                                                                                              |                                                                          |                                                                                               |
| Clarity/Accessibility (8 point) | Prepared   content is easily understandable and accessible                            | Prepared   content is somewhat unclear, key details/explanations omitted                                     | Prepared   content difficult to follow without prior knowledge           | Prepared   content difficult to understand                                                    |
| Understanding (16 marks)        | Content   reflects understanding of main points of paper                              | Content   reflects understanding of some main points of paper, other points missed or   not quite understood | Content   has major errors or oversights of main points                  | Content   lacks main points of paper, or reflects serious misunderstanding of   ideas/methods |
| Organization (8 marks)          | Presentation   organized in logical order, easy to follow                             | Presentation   organized, but some portions out of place                                                     | Presentation   jumps from topics, difficult to follow                    | Poor   organization makes it difficult to follow presentation                                 |
| Presentation   Style (16 marks) |                                                                                       |                                                                                                              |                                                                          |                                                                                               |
|                                 |                                                                                       |                                                                                                              |                                                                          |                                                                                               |
| Speaking (8 marks)              | Presenters   speak clearly at a good pace, easy to understand, keep listeners engaged | Presenters   speak clearly, but a bit dry, too fast, or too slow                                             | Presenters   sometimes lose listeners because of poor pacing or delivery | Speaking   style severely impedes understanding                                               |
| Visuals/handouts (8 marks)      | Prepared   visuals/handouts reflect content, visually appealing, easy to interpret    | Prepared   visuals/handouts wordy or sparse, have minor errors                                               | Prepared   visuals/handouts are limited, add little to presentation      | No   prepared visuals/handouts, or quality is very poor                                       |
